Blazor wasm example addition
johnpapa/hello-worlds pull request #119
Opened 2020-07-18 15:49 UTC by spboyer

By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [X] only the most simple basic hello world app
- [X] remove all tests and commands for tests and dependencies for tests
- [X] must say "Hello World" on the main component
- [X] only include the minimal components (1 ideally)
- [X] no routing, not extras whatsoever
- [X] no styling
- [X] nothing else !
- [X] must work by running `npm install` and `npm start` (or equivalent)
- [X] must be in the folder named `<tech-name>`
- [X] add build steps and which folder to serve in the README.md
- [X] verify that the app once built can be served from whatever folder the built assets are placed in
- [X] verify that running ~~`npx http-server <your-folder-to-serve>` works~~ `dotnet run` in this case
- [X] verify that a Pull Request doesn't already exist. If it does, feel free to contribue to it.

Closes #118

2020-07-20 17:40 UTC, johnpapa commented
@spboyer please add the steps to the main readme in the root of the repo.

2020-07-21 20:06 UTC, manekinekko commented
Thanks a lot @spboyer 

I understand the `dotnet` SDK is required to build the app. Do you think we can have it installed from npm? I found this package published by Microsoft, will it work: https://www.npmjs.com/package/dotnet-3.1?

2020-07-21 20:11 UTC, spboyer commented
@manekinekko - this package is not an official Microsoft npm package and breakage would be likely.  I would not suggest installing it from npm no more that I'd recommend installing a node app from .NET

2020-07-22 11:59 UTC, manekinekko commented
@spboyer gotcha!

@johnpapa would this be a blocker when deploying this Hello World app on SWA?

2020-07-22 12:44 UTC, spboyer commented
@manekinekko Blazor support in SWA is not fully implemented. We are heads down getting that support completed.

2020-07-24 00:22 UTC, danroth27 requested changes
Thanks for contributing this!

2020-07-24 00:22 UTC, danroth27 commented on blazor/Pages/Index.razor
> +<div>Hello World!</div>
Move this markup (without the page directive) into App.Razor and remove the Pages directory.

2020-07-24 00:22 UTC, danroth27 commented on blazor/App.razor
> +<Router AppAssembly="@typeof(Program).Assembly">
No routing allowed! :smile:

2020-07-24 00:22 UTC, danroth27 commented on blazor/App.razor
> +</Router>
```suggestion
<div>Hello, world!</div>
```

2020-08-04 14:10 UTC, spboyer commented on blazor/App.razor
> +</Router>
Thanks!

2020-08-11 15:32 UTC, spboyer commented
@johnpapa @manekinekko - Ok to merge here.

2020-08-11 15:49 UTC, manekinekko approved these changes
Lgtm

2021-03-10 17:25 UTC, spboyer commented
Still needed? @johnpapa

2021-03-10 19:57 UTC, merged

2021-03-10 19:57 UTC, manekinekko commented
Thank you @spboyer. Merged.